`You beg and get ${r} shards for 1 day worth of begging!`,
`Eh you tell your friend you don't have money so they give you ${r} shards!`,
`You were begging for shards in the street, because you we're homeless, and then a stranger came to you and donated ${r} shards!`,
`You worked as a waiter, and got ${r} shards as tip because you served well.`,
`You made a npm package and got ${r} shards as a patreon donation.`,
`You beg your friend for shards and earned ${r} shards`,
`You had no shards left, so you begged and got ${r} shards.`,
`You begged jeff bezos for shards and he gave you ${r} shards.`,
`Sneaky finally gave into you begging and gave you ${r} shards.`,
`You created a server with sneakyhub and someone donated ${r} shards!`,
`You begged the Government for shards so he gave you ${r} shards.`,
`You Begged For Humanity And Humans Gave You ${r} shards`,
`You have begging work and begged ${r} shards.`,
`You were begging for shards to your mom because you want to buy robux card and she gave you ${r} shards.`,
`You were begging in the street, but stranger gave you ${r} shards to buy some food.`,
`You were begging at a place near MrBeast Burger so MrBeast gave you ${r} shards.`,
`You were begging for shards because you want to buy Mcdonald's chicken and someone gave you **${r}** shards.`,
`You begged to a microsoft team member and he gave you ${r} shards.`,
`You were begging for shards in the street, because you we're homeless, and then a stranger came to you and donated ${r} shards!`,
`You were home alone and you had nothing to eat so you begged your neighbor and they gave you ${r} shards`,
`You decided to stand outside walmart to beg and got ${r} shards`,
`You want to buy a VPS so you begged your mom and got ${r} shards.`,
`You begged to win the earn reply ideas contest but you got ${r} shards instead!`,
`You beg enough to earn ${r} shards to pay for a day of hosting!`,
`You were begging in streets and a lady felt bad and gave you ${r} shards!`,
`You asked for a small loan and received ${r} shards!`,
`You begged a rich guy in town and he gave you  ${r} shards!`,
`MrBeast made a visit and gave you ${r} shards!`