`You and your friend has been working as a 7eleven employee and your boss gave you a bonus ${r} shards.`,
`You were working as a lead developer in sneakyhub and sneaky gave you ${r} shards for your hardwork.`,
`You were working for an artist in Los Angeles and got paid ${r} shards.`,
`You helped your school teacher to set up a Discord server for your school and got ${r} shards in return!`,
`You worked so hard for your family. I will give you ${r} shards for working so hard in return!`,
`You made a website for school and got ${r} shards as scholarship.`,
`You donated to SneakyHub and earned ${r} shards.`,
`You developed a good application, and you earned ${r} shards.`,
`You worked for sneaky and you earned ${r} shards.`,
`You woke up being famous and earned ${r} shards.`,
`You had a long and rough day at work and earned ${r} shards.`,
`You got paid ${r} for making sneaky a godly meme!`,
`You worked for MrBeast and helped him to record videos. MrBeast gave you ${r} shards.`,
`You worked for Elon Musk and got paid ${r} shards.`,
`You helped sneaky install new pterodactyl wings, so he gave you ${r} shards.`,
`You worked as a website developer and made a cool website for a company and got rewarded ${r} shards.`,
`You gave a meme to sneaky seeing which sneaky laughed too much and awarded you ${r} shards. Nice meme bro.`,
`You worked for sneaky and helped him to maintain discord and sneaky awarded you ${r} shards.`,
`You helped your school teacher set a Discord server up for your school and got ${r} shards in return!`,
`You made a website for school and got ${r} shards as scholarship.`,
`You helped Sneaky with developing new SneakyHub version. You earned ${r} shards.`,
`You Helped Sneaky By Giving ideas For Earn Command and Earned ${r} shards`,
`You developed a good app. You earned ${r} shards`,
`You collaborated with sneaky and sneaky paid you ${r} shards in return of your help.`,
`You worked as an ethical hacker for google, they were happy they gave you salary of ${r} shards.`,
`You made an application and a user purchased premium in it. So, you got ${r} shards.`,
`You made gfx for sneakyhub and got ${r} shards from sneaky`,
`You tried to make your wife happy and did some extra work. You didnt make anything. She was so mad she threw ${r} shards at you.`,
`You worked as a Discord Moderator without harassing any under-age girl by calling her a kitten and get paid ${r} shards!`,
`You destroyed the ddosers and got paid ${r} shards by sneaky!`,
`You work on Minecraft Server Developer and your boss give you ${r} shards`,
`You helped Sneaky to setup DE1 Node so he gave you ${r} coins!`,
`You made a discord bot and sold its source code for ${r} shards.`,
`You dropped your boss to the airport and he gave you ${r} shards for your effort.`,
`You worked hard as a waiter and got tip of ${r} shards.`,
`You worked so hard all the time for your company so they gave you ${r} shards as a profit.`,
`You worked as a computer teacher and received a payment of ${r} shards.`,
`You helped Prof. Erik Demaine from MIT write a research paper on the theory of general relativity and earned ${r} shards!`,
`Someone crashed your car on the way to work. They gave you ${r} to cover the repair costs.`,
`You repaired someone's vehicle and got ${r} shards.`,
`You Found A Beggar On Road Whom You Gave Some shards And Found Its A Prank In Return You Got ${r} shards.`,
`You were going around streets and you found some people fighting, you stopped their fight and in return you got ${r} shards.`,
`You worked for mining bitcoins and in return you earned ${r} shards by selling them.`,
`You Found A Criminal On The Road on whom bounty was ${r} shards, you called the police and got the bounty.`,
`You worked as a pizza delivery boy and you received a ${r} tip.`,
`You helped a Lawyer and he gave you ${r} shards for the work.`,
`You worked as a tailor and stitched clothes straight 12 hours to earn ${r} shards.`,
`You found and injured woman on the road, you stole her purse and got ${r} shards from the purse.`